<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="<?= $this->asset("static/css/bootstrap.min.css") ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->asset("static/css/tomorrow.min.css") ?>" id="tomorrow" />
        <link rel="stylesheet" type="text/css" href="<?= $this->asset("static/css/tomorrow-night.min.css") ?>" id="tomorrow-night" disabled />
        <link rel="stylesheet" type="text/css" href="<?= $this->asset("static/css/style.css") ?>" />
    </head>
    <body>
        <header class="navbar navbar-default navbar-fixed-top">
            <div id="top-bar" class="container-fluid">
                <div id="top-left" class="navbar-header">
                    <a href="<?= $this->url("/index.html") ?>" class="navbar-brand">
                        <?php if ($this->themeOption("title")){ ?>
                            <?= str_replace( array("%_name_%", "%_version_%") , array($this->projectConfig("name"), $this->projectConfig('version')) , $this->themeOption("title")) ?>
                        <?php }else{ ?>
                            <?= $this->projectConfig("name") ?> Documentation <span class="version">v<?php echo $this->projectConfig('version'); ?></span>
                        <?php } ?>
                    </a>
                </div>
                <div id="top-right" class="collapse navbar-collapse">

                </div>
            </div>
        </header>
        <div id="body" class="container-fluid">
            <div class="row">
                <div id="body-left" class="col-lg-3 col-sm-4">
                    <div class="header-search">
                        <input class="search-box form-control" placeholder="Search for a class or namespace " type="text" />
                        <div id="menu-wrapper">
                        </div>
                    </div>
                </div>
                <div id="body-right" class="col-lg-9 col-sm-8">
                    <div class="content">
                        <?= $this->partial($contentPartial) ?>
                    </div>
                </div>
            </div>
        </div>

        <script src="<?= $this->asset("static/js/jquery.min.js") ?>"></script>
        <script src="<?= $this->asset("static/js/bootstrap.min.js") ?>"></script>
        <script src="<?= $this->asset("static/js/highlight.pack.js") ?>"></script>
        <script src="<?= $this->asset("static/js/jquery.slimscroll.min.js") ?>"></script>
        <script src="<?= $this->asset("api_definition.js") ?>"></script>

        <script>var ZepCurrentPath = '<?=$this->url("/")?>'</script>
        <script src="<?= $this->asset("static/js/script.js") ?>"></script>
        <script type="text/javascript">
            $(window).on("load resize", function() {
                $('#menu-wrapper').slimscroll({ height: $(window).height(), size: '3px' });
            });
        </script>
        <script type="text/javascript">
            $(document).ready(function() { $('pre code').each(function(i, block) { hljs.highlightBlock(block); }); });
            if ($('.zephir-source-file').length) {
                $('link[id]').each(function(i, link) {
                    link.disabled = (link.id != 'tomorrow-night');
                });
            }
        </script>
        <?php if($this->themeOption("analytics")){ ?>
        <!-- Google Analytics -->
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', '<?= $this->themeOption("analytics") ?>', 'auto');
            ga('send', 'pageview');
        </script>
        <!-- End Google Analytics -->
        <?php } ?>
    </body>
</html>