<?php

    $items = array(
        array("name" => "Classes" , "url" => "/classes.html" ),
        $items[] = array("name" => $fullName)
    );
?>

<?= $this->partial("partials/breadcrumb.phtml",array("items"=> $items)) ?>

<div class="class-header clearfix">
    
    
    <div class="access-buttons pull-right">
        <a class="zep-button btn btn-default" href="<?= $this->url(Zephir\Documentation::sourceUrl($classDefinition)) ?>">Source</a>

        <?php if($this->themeOption("github")){ ?>
        <a class="zep-button btn btn-default" href="<?= $this->themeOption("github") . "/tree/dev/" . $compilerFile->getFilePath() ?>">Github</a>
        <?php } ?>
    </div>
    
    <div class="class-full-name">
        
        <span class="class-type">Class</span>
        
        <?php foreach($namespacePieces as $nsname => $nspath){ ?>
        <span class="namespace-piece">
            <a href="<?= $this->url(Zephir\Documentation::namespaceUrl($nspath)) ?>"><?=$nsname?></a>
        </span>
        <?php } ?>
        <h1 class="class-name"><?= $className ?></h1>
    </div>

</div>


<div class="hidden-anchor"  id="methods"></div>
<div class="methods-summary standard-bandeau">Methods</div>
<table class="method-summary-list table table-striped table-hover">
    <?php foreach($methods as $method){ ?>

        <?= $this->partial("partials/class/method-summary.phtml",array("method"=>$method)) ?>

    <?php } ?>
</table>

<div class="hidden-anchor"  id="methods-details"></div>
<div class="methods-summary standard-bandeau">Methods Details</div>
<ul class="method-details-list list-unstyled">
    <?php foreach($methods as $method){ ?>

        <?= $this->partial("partials/class/method-details.phtml",array("method"=>$method)) ?>

    <?php } ?>
</ul>